version: 2.1
jobs:
  build:
    working_directory: ~/automated-tests
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install gulp
          command: 'sudo npm i -g gulp-cli'
      - run:
          name: Install dependencies
          command: 'npm i'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  test:
    docker:
      - image: circleci/node:8
    steps:
      - run:
          name: Test
          command: 'gulp'
      - store_artifacts:
          path: ~/automated-tests/tmp/report.html

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
          pre:
            - ./node_modules/.bin/gulp
            - ./node_modules/gulp/bin/gulp.js
            - node node_modules/gulp/bin/gulp.js